### ISSUE TITLE
GWAS: Update to new file format

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/humanmine-bio-sources#2]
Class | Field | Column number
------------ | ------------- | -------------
GWAS | First Author | 2
GWAS | Initial sample | 8
GWAS | Name | 6
GWAS | Replicate sample | 9
GWAS | Year (change to date or extract?):  | 3
RESULTS | Associated variant risk allele | 20
RESULTS | Phenotype | 7
RESULTS | P value | 27
RESULTS | Risk allele frequency in controls | 26
RESULTS | (add context? | 24 )
GENE | ASSOCIATED GENE | 17
SNP | Primary identifier | 21
PUBLICATION | pubmed id | 1

**Comment by julie-sullivan** [comment]
`rs143409503--` - Associated variant risk allele value

**Comment by sergiocontrino** [comment]
it should be fine
